id: P009454
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4608
  title: ཕྱག་ཆེན་སྔོན་འགྲོ་ཐུན་མོང་གི་ཁྲིད་ཡིག་གསེར་གྱི་ཐིགས་པ་
  author: ''
  volumes:
    d6ad25aaa541477298ef9a741b161f39:
      image_group_id: I1KG4614
      title: ''
      volume_number: 1
      total_pages: 518
