id: P009454
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-19 19:39:33.257602
source_metadata:
  id: bdr:W1KG4608
  title: ཕྱག་ཆེན་སྔོན་འགྲོ་ཐུན་མོང་གི་ཁྲིད་ཡིག་གསེར་གྱི་ཐིགས་པ་
  author: ''
  volumes:
    d6ad25aaa541477298ef9a741b161f39:
      image_group_id: I1KG4614
      title: ''
      volume_number: 1
      total_pages: 518
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
